#! /usr/bin/env python

'''
Name albums
'''

import sys
import os
import argparse
import subprocess
import tempfile
import logging
import re
import yaml
import exifread
import tqdm

GOODRE = re.compile(r'^\d{4}(?:-\d\d(?:-\d\d)?)? ')
RETIME = re.compile(r'[ :]')

def getexiftime(othertags, tags):
    '''
    Get time from EXIF
    '''

    for tag in 'EXIF DateTimeOriginal', 'Image DateTime':
        if tag in tags:
            return RETIME.split(str(tags[tag]))
    othertags.update(set(tags))


def exreport(tmp, dryrun):
    '''
    Execute report
    '''

    with open(tmp.name) as fhl:
        src = None
        for line in fhl:
            line = line.strip()

            if line and not src:
                src = line
            elif src and line.startswith('@mv '):
                dst = line[4:]
                if src != dst and not os.path.lexists(dst):
                    print 'mv "%s" "%s"' % (src, dst)
                    if not dryrun:
                        os.rename(src, dst)
                else:
                    print >> sys.stderr, "%s already exists" % dst
            elif not line:
                src = None


def mksampling(sampling, othertags, otherexts, root, files):
    '''
    Make sampling
    '''

    for fle in files:
        path = '%s/%s' % (root, fle)

        # Strip against files with trailing space
        ext = os.path.splitext(fle)[1][1:].strip().lower()
        if ext in ('jpg', 'jpeg', 'png', 'tif', 'tiff', 'cr2', 'nef'):
            try:
                with open(path) as fhl:
                    tags = exifread.process_file(fhl)
                    if tags:
                        time = getexiftime(othertags, tags)
                        if time:
                            if time < sampling['oldest']:
                                sampling['oldest'] = time
                            if time > sampling['newest']:
                                sampling['newest'] = time
                            break
            except IOError:
                pass
        else:
            otherexts.add(ext)


def report(tmp, album, sampling):
    '''
    Report
    '''

    # Print tree
    # Setting stdout to tmp appears to overwrite part of tmp
    proc = subprocess.Popen(['tree', '--noreport', album],
                            stdout=subprocess.PIPE)
    for line in proc.stdout:
        print >> tmp, line,

    # Print suggestion
    if sampling['newest'] == ['0']:
        print >> tmp, "mv %s" % album
    else:
        print >> tmp, "From %s-%s-%s to %s-%s-%s" % \
            (sampling['oldest'][0],
             sampling['oldest'][1],
             sampling['oldest'][2],
             sampling['newest'][0],
             sampling['newest'][1],
             sampling['newest'][2])
        print >> tmp, "mv %s/%s-%s-%s %s" % \
            (os.path.dirname(album),
             sampling['oldest'][0],
             sampling['oldest'][1],
             sampling['oldest'][2],
             os.path.basename(album))

    print >> tmp


def main():
    '''
    Main loop
    '''

    # Parse arguments
    parser = argparse.ArgumentParser(description="Name albums.")
    parser.add_argument('directory', nargs='+', help="album directory")
    parser.add_argument('--dryrun', action='store_true')
    args = parser.parse_args()

    # Load config
    try:
        with open(os.path.expanduser('~/.namegalleries.yaml')) as fhl:
            cfg = yaml.load(fhl)
    except IOError:
        cfg = {}

    # Hide messages from tqdm
    logging.basicConfig(level=logging.CRITICAL)

    # Open temporary file
    tmp = tempfile.NamedTemporaryFile()

    # Find files
    othertags = set()
    otherexts = set()
    for album in tqdm.tqdm(args.directory):
        if os.path.isdir(album) and not GOODRE.match(os.path.basename(album)):
            sampling = {'oldest': ['9'], 'newest': ['0']}
            for root, _, files in os.walk(album):
                mksampling(sampling, othertags, otherexts,
                           root, sorted(files))
                mksampling(sampling, othertags, otherexts,
                           root, sorted(files, reverse=True))

            # Write to report
            report(tmp, album, sampling)

    # Report on other tags
    if othertags:
        print >> tmp, "Couldn't always find expected time tags. Found:"
        for tag in othertags:
            print >> tmp, "    %s" % tag

    # Report on other extensions
    if otherexts:
        print >> tmp, "Skipped extensions:"
        for ext in otherexts:
            print >> tmp, "    '%s'" % ext

    # Review and execute report
    tmp.flush()
    subprocess.call(['vim', '+set ft=namegalleries', tmp.name])
    exreport(tmp, args.dryrun)


if __name__ == '__main__':
    sys.exit(main())
